language: php
sudo: required
env: TRAVIS_PUBLIC_REPOSITORY=true
dist: trusty
php:
  - 7.0
  - 7.1

matrix:
  fast_finish: true

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable

addons:
  chrome: stable

cache:
  apt: true
  directories:
    - "node_modules"
    - $HOME/.composer/cache/files

before_script:
- sudo apt-get update
- sudo apt-get install apache2 libapache2-mod-fastcgi

# enable php-fpm
- sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
- sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf
- sudo a2enmod rewrite actions fastcgi alias
- echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars
- sudo chown -R travis:travis /var/lib/apache2/fastcgi
- ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm

# configure apache virtual hosts
- sudo cp -f ./tests/travis-ci-apache.conf /etc/apache2/sites-available/000-default.conf
- sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
- sudo service apache2 restart

# Get ChromeDriver for headless mode
- wget "https://chromedriver.storage.googleapis.com/2.38/chromedriver_linux64.zip"
- unzip "chromedriver_linux64.zip"
- mkdir -p /usr/local/bin
- sudo cp -a chromedriver /usr/local/bin
- sudo chmod +x /usr/local/bin/chromedriver

# Build extension
- cd build
- npm install
- mv gulp-config.json.dist gulp-config.json
- node_modules/.bin/gulp release --skip-version
- cd ../tests

# Generic RoboFile init file
- mv RoboFile.ini.dist RoboFile.ini

script:
- composer install --prefer-dist
- mv acceptance.suite.dist.yml acceptance.suite.yml
- mv api.suite.dist.yml api.suite.yml

- vendor/bin/robo run:tests 0 null false
- vendor/bin/robo run:unit-tests

#notifications:
#  slack:
#    secure: AeKLAsle7sQ3lGpXeNk0ePovlnf0QTggiKhHuvEH78TD5aN8OjYEqbLBhFWWcejn4hHWHOeR9pUv0wqClEGirMioWI5noQvE6D6bV9oBrAhx2FKLVxCA3YN23i+ehNpk3+FpVhkmagigiEnPZqqFcqFw5x276GVZTC8etNmzs/w=
